#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Repository path   : $HeadURL:  $
# Last committed    : $Revision:  $
# Last changed by   : $Author:  $
# Last changed date : $Date: $
#

import tmEditor

from PyQt4.QtGui import QApplication
import argparse
import logging
import sys, os

EXIT_OK = 0
EXIT_FAIL = 1

def parse():
    parser = argparse.ArgumentParser()
    return parser.parse_args()

def main():
    """Main routine."""
    args = parse()
    try:
        app = QApplication(sys.argv)
        window = tmEditor.MainWindow()
        window.show()
        return app.exec_()
    except RuntimeError, message:
        logging.error(message)
        return EXIT_FAIL
    return EXIT_OK

if __name__ == '__main__':
    sys.exit(main())
