#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Repository path   : $HeadURL:  $
# Last committed    : $Revision:  $
# Last changed by   : $Author:  $
# Last changed date : $Date: $
#

from tmEditor.core import XmlDecoder, XmlEncoder
from tmEditor.gui.MainWindow import MainWindow
from tmEditor.version import VERSION, PKG_RELEASE

from PyQt4.QtCore import QSettings, QTimer, QT_VERSION_STR
from PyQt4.QtGui import QApplication

import argparse
import logging
import signal
import sys, os

EXIT_OK = 0
EXIT_FAIL = 1

def parse():
    """Command line argument parser."""
    parser = argparse.ArgumentParser()
    parser.add_argument('filenames',
        metavar = '<file>',
        nargs = '*',
        help = "trigger menu XML file",
    )
    parser.add_argument('--export-xml',
        metavar = '<file>',
        help = "export normalized document to XML file",
    )
    parser.add_argument('--timeout',
        metavar = '<sec>',
        type = int,
        default = 10,
        help = "timeout for remote connections in seconds (default 10)",
    )
    parser.add_argument('-v', '--verbose',
        action = 'count',
        help = "increase output verbosity",
    )
    parser.add_argument('-V', '--version',
        action = 'version',
        version = "%(prog)s {0}-{1}".format(VERSION, PKG_RELEASE),
        help = "show the application's version",
    )
    return parser.parse_args()

def export_xml(args):
    """Export normalized document to XML file."""
    if not args.export_xml:
        message = "argument `--export-xml' requires a XML file to be loaded"
        raise RuntimeError(message)
    if not args.filenames:
        message = "argument `--export-xml' requires a XML file to be loaded"
        raise RuntimeError(message)
    menu = XmlDecoder.load(args.filenames[0])
    # Check integrity
    menu.validate()
    XmlEncoder.dump(menu, args.export_xml)
    return EXIT_OK

def main():
    """Main application routine."""
    # Parse arguments.
    args = parse()

    # Setup console logging and debug level.
    loggingLevel = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(format='%(levelname)s: %(message)s', level=loggingLevel)

    # As things are getting serious let's start logging to file.
    if args.verbose:
        filename = os.path.expanduser('~/tm-editor.log')
        if os.access(filename, os.W_OK): # is writable?
            handler = logging.FileHandler(filename, mode='a')
            handler.setFormatter(logging.Formatter(fmt='%(asctime)s %(levelname)s : %(message)s', datefmt='%Y-%m-%d %H:%M:%S'))
            handler.setLevel(loggingLevel)
            logging.getLogger().addHandler(handler)

    # Diagnostic output.
    logging.debug("launching L1-Trigger Menu Editor")
    logging.debug("version %s-%s", VERSION, PKG_RELEASE)
    logging.debug("__file__=%s", __file__)
    logging.debug("sys.argv=%s", sys.argv)
    logging.debug("LD_LIBRARY_PATH=%s", os.getenv('LD_LIBRARY_PATH'))
    logging.debug("PATH=%s", os.getenv('HOME'))
    logging.debug("UTM_ROOT=%s", os.getenv('UTM_ROOT'))
    logging.debug("UTM_XSD_DIR=%s", os.getenv('UTM_XSD_DIR'))
    logging.debug("LC_ALL=%s", os.getenv('LC_ALL'))
    logging.debug("python version %s.%s.%s", *sys.version_info[:3])
    logging.debug("PyQt4 version %s", QT_VERSION_STR)

    # Export options
    if args.export_xml:
        return export_xml(args)

    # Create application window.
    try:
        app = QApplication(sys.argv)

        # Create/Load application settings.
        app.setOrganizationName("HEPHY")
        app.setOrganizationDomain("hephy.at")
        app.setApplicationName("Trigger Menu Editor")

        # Init global settings.
        QSettings()

        # Create main window.
        window = MainWindow()
        window.setRemoteTimeout(args.timeout)
        window.show()

        # Load documents from command line (optional).
        for filename in args.filenames:
            logging.debug("loading file %s", filename)
            window.loadDocument(filename)
            app.processEvents()

        # Terminate application on SIG_INT signal.
        signal.signal(signal.SIGINT, signal.SIG_DFL)

        # Run timer to catch SIG_INT signals.
        timer = QTimer()
        timer.start(500)
        timer.timeout.connect(lambda: None)

        return app.exec_()
    except RuntimeError, message:
        logging.error(message)
        return EXIT_FAIL
    return EXIT_OK

if __name__ == '__main__':
    sys.exit(main())
